version: '3'
services:
  myapp-main:
    image: golf-club-api:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/golf_QAP
      - spring.datasource.username=root
      - spring.datasource.password=Keyin2024